### ISSUE TITLE
https://github.com/kingqabil/book-an-appointment-backend/projects/1

### ISSUE THREAD

**Issue by Lockless404** [kingqabil/-book-an-appointment-frontend#14]
2 Students in the project:
- Hamza Tarar
- Sadiq Habil
![kanban-1](https://user-images.githubusercontent.com/79739022/169855174-6d887ec6-6132-4b49-b303-5f026062ba13.png)

**Comment by MuriloRoque** [comment]
Hi @Lockless404, @kingqabil, @AtillaTahak,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
